## Numpy 
Numpy is a python library for scientific computing — to work with multidimensional array objects and used to handle large amount of data. An array which is a grid of values and is indexed by a tuple of nonnegative integers is main data structure of the Numpy library. `ndarray` is acronym of N-Dimensional Array.


### import Numpy

In [2]:
import numpy as np

### Create Numpy Arrays

In [4]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

### Zeros arrays
Returns a new array setting values to 0

In [5]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.zeros(7, dtype=int)

array([0, 0, 0, 0, 0, 0, 0])

### Ones arrays
Return a new array of given shape and type all field with 1

In [8]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [9]:
np.ones((3, 5), dtype="int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### Full arrays
Return a new array of given shape filled with a specific value

In [10]:
np.full((3, 6), 9)

array([[9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9]])

### Identity Matrix

In [11]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Reshape

In [12]:
np.arange(1, 15).reshape(2, 7)

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [13]:
np.arange(1, 10).reshape((1, 9))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

### Flattening the Arrays
Convert multidimensional array into 1D array

In [14]:
a2 = np.arange(1, 9).reshape((1, 8))
a2.reshape(-1)
a2.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

### Concatenation
Combine together two numpy arrays.

In [15]:
a1 = np.array([100, 110, 140])
a2 = np.array([120, 121, 220])
np.concatenate([a1, a2])

array([100, 110, 140, 120, 121, 220])

In [16]:
arr1 = np.array([[10, 20, 30],
                 [40, 50, 60]])
arr2 = np.array([[101, 102, 103],
                 [104, 105, 106]])
np.concatenate([arr1,arr2])

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [101, 102, 103],
       [104, 105, 106]])

### Broadcasting
It’s a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations.

*   If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
*   The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
*   The arrays can be broadcast together if they are compatible in all dimensions.
*   After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
*   In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

In [17]:
arr1 = np.array([1, 0, 1])
arr2 = np.array([1])
arr1 + arr2

array([2, 1, 2])

### Scalar Product
It takes two equal-length sequences of numbers and returns a single number.

In [18]:
arr1 = np.array([[30, 15],
                 [19, 42]]) 
arr2 = np.array([[101, 90],
                 [45, 64]])
np.dot(arr1,arr2)

array([[3705, 3660],
       [3809, 4398]])